// Generated by CoffeeScript 2.0.0-beta7
jQuery(function () {
  $('#slide_index .slide-link.f').hover(function () {
    return $(this).parents('.content').css('background-image', 'url(img/index-triangle-f.png)');
  }, function () {
    return $(this).parents('.content').css('background-image', 'url(img/index-triangle.png)');
  });
  $('#slide_index .slide-link.t').hover(function () {
    return $(this).parents('.content').css('background-image', 'url(img/index-triangle-t.png)');
  }, function () {
    return $(this).parents('.content').css('background-image', 'url(img/index-triangle.png)');
  });
  $('#slide_index .slide-link.th').hover(function () {
    return $(this).parents('.content').css('background-image', 'url(img/index-triangle-th.png)');
  }, function () {
    return $(this).parents('.content').css('background-image', 'url(img/index-triangle.png)');
  });
  return $('#slide_index .slide-link.fo').hover(function () {
    return $(this).parents('.content').css('background-image', 'url(img/index-triangle-fo.png)');
  }, function () {
    return $(this).parents('.content').css('background-image', 'url(img/index-triangle.png)');
  });
});
