// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var OnResizeCalled;
  OnResizeCalled = function () {
    var wHeight, wWidth;
    console.log(1);
    wHeight = window.innerHeight;
    wWidth = innerHeight / 3 * 4;
    return $('.slide article').css({
      width: wWidth,
      height: wHeight,
      marginLeft: wWidth / 2 * -1
    });
  };
  window.addEventListener('resize', OnResizeCalled, false);
  jQuery(function () {
    OnResizeCalled();
    $('#splashImg').splashScreen({
      textLayers: [
        'img/splash-0.png',
        'img/splash-1.png',
        'img/splash-2.png',
        'img/splash-3.png',
        'img/splash-4.png'
      ]
    });
    $('#slide_pmarketing figure').on('mouseover', function () {
      $(this).find('img').not('[rel=img]').stop().fadeTo('slow', 0);
      $(this).find('figcaption').hide();
      return $(this).find('[rel=img]').stop().fadeTo('slow', 1);
    });
    return $('#slide_pmarketing figure').on('mouseout', function () {
      $(this).find('[rel=img]').stop().fadeTo('fast', 0);
      $(this).find('img').not('[rel=img]').stop().fadeTo('fast', 1);
      return $(this).find('figcaption').show();
    });
  });
}.call(this);
