// Generated by CoffeeScript 2.0.0-beta7
jQuery(function () {
  return $('#splashImg').splashScreen({
    textLayers: [
      'img/splash-0.png',
      'img/splash-1.png',
      'img/splash-2.png',
      'img/splash-3.png',
      'img/splash-4.png'
    ]
  });
});
