// Generated by CoffeeScript 2.0.0-beta7
jQuery(function () {
  var button, goToByScroll, htmlbody, links, mywindow, slide;
  $(window).stellar({
    horizontalScrolling: true,
    verticalScrolling: true,
    parallaxBackgrounds: true,
    parallaxElements: true,
    verticalOffset: 0,
    horizontalOffset: 0,
    hideDistantElements: true
  });
  links = $('.slide-link');
  slide = $('.slide');
  button = $('.button');
  mywindow = $(window);
  htmlbody = $('html,body');
  slide.waypoint(function (event, direction) {
    var dataslide;
    dataslide = $(this).attr('data-slide');
    if (direction === 'down') {
      return $('.navigation li[data-slide="' + dataslide + '"]').addClass('active').prev().removeClass('active');
    } else {
      return $('.navigation li[data-slide="' + dataslide + '"]').addClass('active').next().removeClass('active');
    }
  });
  mywindow.scroll(function () {
    if (mywindow.scrollTop() === 0) {
      $('.navigation li[data-slide="1"]').addClass('active');
      return $('.navigation li[data-slide="2"]').removeClass('active');
    }
  });
  goToByScroll = function (dataslide, orientation) {
    if (orientation === 'vertical') {
      return htmlbody.animate({ scrollTop: $('.slide[data-slide="' + dataslide + '"]').offset().top }, 2e3, 'easeInOutQuint');
    } else if (orientation === 'horizontal') {
      return htmlbody.animate({ scrollLeft: $('.slide[data-slide="' + dataslide + '"]').offset().left }, 2e3, 'easeInOutQuint');
    }
  };
  links.click(function (e) {
    var dataslide, orientation;
    e.preventDefault();
    dataslide = $(this).attr('data-slide');
    orientation = $(this).attr('data-orientation') || 'horizontal';
    goToByScroll(dataslide, orientation);
    return false;
  });
  return button.click(function (e) {
    var dataslide, orientation;
    e.preventDefault();
    dataslide = $(this).attr('data-slide');
    orientation = $(this).attr('data-orientation') || 'horizontal';
    return goToByScroll(dataslide, orientation);
  });
});
