// Generated by CoffeeScript 2.0.0-beta7
jQuery(function () {
  parallax.add($('#slide_index')).add($('#slide_agency')).add($('#slide_services')).add($('#slide_mission')).add($('#slide_budda')).add($('#slide_worth')).add($('#slide_contacts')).add($('#slide_development')).add($('#slide_marketing')).add($('#slide_pmarketing'));
  parallax.background = $('body');
  $('.slide-link, .button').on('click', function () {
    var direction, slide;
    parallax.speed = 2e3;
    parallax.easing = 'easeInOutQuint';
    parallax.scaling = .9;
    slide = 'slide_' + $(this).attr('data-slide');
    direction = $(this).attr('data-direction');
    if (direction === 'top')
      parallax[slide].top();
    if (direction === 'bottom')
      parallax[slide].bottom();
    if (direction === 'left')
      parallax[slide].left();
    if (direction === 'right')
      return parallax[slide].right();
  });
  return parallax.slide_index.show();
});
